DROP TABLE PHOTOBOX_PICTURE;
DROP TABLE PHOTOBOX_FOLDER;
DROP TABLE PRIMARY_KEY_SEQ;

CREATE TABLE PHOTOBOX_PICTURE (
  ID INT NOT NULL,
  NAME VARCHAR(1024),
  CAPTURE_DATE DATE,
  FOLDER_ID INT NOT NULL,
  ROTATION INT,
  PATH_ORIGINAL VARCHAR(1024),
  PATH_SMALL VARCHAR(1024),
  PATH_MEDIUM VARCHAR(1024),
  PATH_LARGE VARCHAR(1024),
  ACTIVE BOOLEAN NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE PHOTOBOX_FOLDER (
  ID INT NOT NULL,
  PARENT_ID INT NOT NULL,
  NAME VARCHAR(1024),
  ACTIVE BOOLEAN NOT NULL,
  PATH_ORIGINAL VARCHAR(1024),
  PRIMARY KEY (ID)
);
  
CREATE TABLE PRIMARY_KEY_SEQ (LAST_VAL BIGINT);

INSERT INTO PRIMARY_KEY_SEQ (LAST_VAL) VALUES (5);



