DROP TABLE PHOTOBOX_PICTURE;
DROP TABLE PHOTOBOX_FOLDER;
DROP TABLE PHOTOBOX_NAVIGATION_LINK;
DROP TABLE PRIMARY_KEY_SEQ;


CREATE TABLE PHOTOBOX_PICTURE (
  ID DECIMAL NOT NULL,
  NAME VARCHAR(1024),
  CAPTURE_DATE DATE,
  ROTATION INT,
  PATH_ORIGINAL VARCHAR(1024),
  PATH_SMALL VARCHAR(1024),
  PATH_MEDIUM VARCHAR(1024),
  PATH_LARGE VARCHAR(1024),
  ACTIVE BOOLEAN NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE PHOTOBOX_FOLDER (
  ID DECIMAL NOT NULL,
  NAME VARCHAR(1024),
  ACTIVE BOOLEAN NOT NULL,
  PATH_ORIGINAL VARCHAR(1024),
  PRIMARY KEY (ID)
);

CREATE TABLE PHOTOBOX_NAVIGATION_LINK (
  PARENT_ID DECIMAL NOT NULL,
  CHILD_ID DECIMAL NOT NULL,
  DISTANCE INT,
  PRIMARY KEY (PARENT_ID,CHILD_ID)
);

CREATE TABLE PRIMARY_KEY_SEQ (LAST_VAL BIGINT);

INSERT INTO PRIMARY_KEY_SEQ (LAST_VAL) VALUES (5);



