Select P.NAME, P.PATH_ORIGINAL,  F.NAME from PHOTOBOX_PICTURE P, PHOTOBOX_FOLDER F WHERE P.FOLDER_ID = F.ID

Select * from PHOTOBOX_PICTURE;

UPDATE PHOTOBOX_PICTURE
SET ROTATION = 90
WHERE NAME = 'DSC02241.JPG';